config/routes.rb
Rails.application.routes.draw do
  resources :properties
  get "/dashboard" => "dashboard#index", :as => :dashboard

  root to: "public#main"
  devise_for :account
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :trackable

  has_many :properties

  def full_name
    "#{first_name} #{last_name}"
  end
  def company
    "test Company"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
  has_one_attached :photo
  belongs_to :account

  scope :latest, -> { order created_at: :desc }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:update, keys: %i[first_name last_name url])
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_account!
  before_action :set_sidebar
  def index
  end

  def properties
  end

  def reports
  end
end

private

def set_sidebar
  @show_sidebar = true
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show edit update destroy]
  before_action :authenticate_account!, only: %i[new create destroy]
  before_action :authenticate_account!
  before_action :set_sidebar, except: %i[show]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
    @agent = @property.account
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)
    @property.account_id = current_account.id

    respond_to do |format|
      if @property.save
        format.html do
          redirect_to property_url(@property),
                      notice: "Property was successfully created."
        end
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @property.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html do
          redirect_to property_url(@property),
                      notice: "Property was successfully updated."
        end
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @property.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy

    respond_to do |format|
      format.html do
        redirect_to properties_url,
                    notice: "Property was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sidebar
    @show_sidebar = true
  end

  def set_property
    @property = Property.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def property_params
    params.require(:property).permit(
      :name,
      :address,
      :price,
      :rooms,
      :bath_rooms,
      :details,
      :parking_space,
      :photo
    )
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
    @properties = Property.latest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def property_thumbnail(property, width, height)
    img = property.photo.present? ? property.photo : "placeholder.png"
    image_tag(
      img,
      class: "property-thumb",
      style: "width:#{width} ; height:#{height};"
    )
  end
  def property_photo_full_size(property)
    img = property.photo.present? ? property.photo : "placeholder.png"
    image_tag(img, class: "property-photo")
  end
  def created_before_time(property)
    t = property.created_at
    t.strftime("at %I:%M %p")
  end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/dashboard/index.html.erb
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h3">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
            </div>
            <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                    class="feather feather-calendar align-text-bottom" aria-hidden="true">
                    <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                    <line x1="16" y1="2" x2="16" y2="6"></line>
                    <line x1="8" y1="2" x2="8" y2="6"></line>
                    <line x1="3" y1="10" x2="21" y2="10"></line>
                </svg>
                This week
            </button>
        </div>
    </div>



    <h2>Section title</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Header</th>
                    <th scope="col">Header</th>
                    <th scope="col">Header</th>
                    <th scope="col">Header</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1,001</td>
                    <td>random</td>
                    <td>data</td>
                    <td>placeholder</td>
                    <td>text</td>
                </tr>
                <tr>
                    <td>1,002</td>
                    <td>placeholder</td>
                    <td>irrelevant</td>
                    <td>visual</td>
                    <td>layout</td>
                </tr>
                <tr>
                    <td>1,003</td>
                    <td>data</td>
                    <td>rich</td>
                    <td>dashboard</td>
                    <td>tabular</td>
                </tr>
                <tr>
                    <td>1,003</td>
                    <td>information</td>
                    <td>placeholder</td>
                    <td>illustrative</td>
                    <td>data</td>
                </tr>
                <tr>
                    <td>1,004</td>
                    <td>text</td>
                    <td>random</td>
                    <td>layout</td>
                    <td>dashboard</td>
                </tr>

            </tbody>
        </table>

    </div>

app/views/dashboard/properties.html.erb
<h1>Dashboard#properties</h1>
<p>Find me in app/views/dashboard/properties.html.erb</p>

app/views/dashboard/reports.html.erb
<h1>Dashboard#reports</h1>
<p>Find me in app/views/dashboard/reports.html.erb</p>

app/views/layouts/_validation.html.erb
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DomainClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <!-- CSS only -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", media: "all","data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body id="<%= controller.controller_name%>" class = "<%= controller.action_name%> <%=  "show-sidebar" if @show_sidebar.present? %>">
    <% if @show_sidebar.nil?%>
     <%# ["public","devise","sessions"].include?(controller.controller_name) %>
      <header>
        <%= render "layouts/nav/public"%>
      </header >
       <%= yield %>
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
       <%= render "layouts/footer/public"%>
      </footer>
    <%else%>
      <%= render "layouts/nav/dashboard"%>
       <div class="container-fluid">
        <div class="row">
          <%= render "layouts/nav/sidebar" %>
          <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 mt-3">
            <%= yield %>
          </main>
        </div>
      </div>

    <% end %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.29.0/feather.min.js" integrity="sha512-24XP4a9KVoIinPFUbcnjIjAjtS59PUoxQj3GNVpWc86bCqPuy3YxAcxJrxFCxXe4GHtAumCbO2Ze2bddtuxaRw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>feather.replace()</script>
  </body>
</html>

app/views/layouts/footer/_public.html.erb
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-muted">© 2022 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>

app/views/layouts/nav/_dashboard.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="/">DomainClone</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
        <div class="navbar-nav">
            <div class="nav-item text-nowrap">

            <%= link_to "Sign out",destroy_account_session_path,data: {turbo_method: :delete}, class: "nav-link px-3"%>
            </div>
        </div>
</header>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Property Finder</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <% if account_signed_in?%>
            <%= link_to "Dashboard", dashboard_path, class:"nav-link"%>
            <% else%>
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            <% end%>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Latest</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="#">News</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Advertising</a>
        </li>
        <% if account_signed_in?%>
        <li class = "nav-item">
          <%= link_to "Log out" , destroy_account_session_path,data:{ turbo_method: :delete},class: "nav-link"%>
        </li>
        <%else%>
        <li class="nav-item">
          <%= link_to "Log in", new_account_session_path, class: "nav-link"%>
        </li>
          <li class="nav-item">
          <%= link_to "Sign up", new_account_registration_path, class: "nav-link"%>
        </li>
        <%end%>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <%= link_to dashboard_path, class: "nav-link"  do %>
                   <i data-feather= "home"></i>
                    Dashboard
                <%end%>
            </li>
            <li class="nav-item">
               <%= link_to properties_path,  class: "nav-link" do %>
                    <i data-feather= "package"></i>
                    Properties
                <%end%>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-shopping-cart align-text-bottom" aria-hidden="true">
                        <circle cx="9" cy="21" r="1"></circle>
                        <circle cx="20" cy="21" r="1"></circle>
                        <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path>
                    </svg>
                    Products
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-users align-text-bottom" aria-hidden="true">
                        <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                        <circle cx="9" cy="7" r="4"></circle>
                        <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                        <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                    </svg>
                    Customers
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-bar-chart-2 align-text-bottom" aria-hidden="true">
                        <line x1="18" y1="20" x2="18" y2="10"></line>
                        <line x1="12" y1="20" x2="12" y2="4"></line>
                        <line x1="6" y1="20" x2="6" y2="14"></line>
                    </svg>
                    Reports
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-layers align-text-bottom" aria-hidden="true">
                        <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
                        <polyline points="2 17 12 22 22 17"></polyline>
                        <polyline points="2 12 12 17 22 12"></polyline>
                    </svg>
                    Integrations
                </a>
            </li>
        </ul>

        <h6
            class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
            <span>Saved reports</span>
            <a class="link-secondary" href="#" aria-label="Add a new report">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                    class="feather feather-plus-circle align-text-bottom" aria-hidden="true">
                    <circle cx="12" cy="12" r="10"></circle>
                    <line x1="12" y1="8" x2="12" y2="16"></line>
                    <line x1="8" y1="12" x2="16" y2="12"></line>
                </svg>
            </a>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-file-text align-text-bottom" aria-hidden="true">
                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                        <polyline points="14 2 14 8 20 8"></polyline>
                        <line x1="16" y1="13" x2="8" y2="13"></line>
                        <line x1="16" y1="17" x2="8" y2="17"></line>
                        <polyline points="10 9 9 9 8 9"></polyline>
                    </svg>
                    Current month
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-file-text align-text-bottom" aria-hidden="true">
                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                        <polyline points="14 2 14 8 20 8"></polyline>
                        <line x1="16" y1="13" x2="8" y2="13"></line>
                        <line x1="16" y1="17" x2="8" y2="17"></line>
                        <polyline points="10 9 9 9 8 9"></polyline>
                    </svg>
                    Last quarter
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-file-text align-text-bottom" aria-hidden="true">
                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                        <polyline points="14 2 14 8 20 8"></polyline>
                        <line x1="16" y1="13" x2="8" y2="13"></line>
                        <line x1="16" y1="17" x2="8" y2="17"></line>
                        <polyline points="10 9 9 9 8 9"></polyline>
                    </svg>
                    Social engagement
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-file-text align-text-bottom" aria-hidden="true">
                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                        <polyline points="14 2 14 8 20 8"></polyline>
                        <line x1="16" y1="13" x2="8" y2="13"></line>
                        <line x1="16" y1="17" x2="8" y2="17"></line>
                        <polyline points="10 9 9 9 8 9"></polyline>
                    </svg>
                    Year-end sale
                </a>
            </li>
        </ul>
    </div>
</nav>

app/views/properties/_agent_details.html.erb
<div class= "">
    <h3 class = "h4"><%= @agent.full_name%></h3>
   <p> <%= @agent.company%></p>
    <button class= "btn btn-info">Contact <%=@agent.first_name %></button>
    <button class= "btn btn-success">Email <%=@agent.first_name %></button>

</div>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
<%= render "layouts/validation", item: @property%>

  <div class = "form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address , class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= form.label :rooms, style: "display: block" %>
    <%= form.number_field :rooms, class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= form.label :bath_rooms, style: "display: block" %>
    <%= form.number_field :bath_rooms , class: "form-control"%>
  </div>
  <div class = "form-group">
    <%= form.label :parking_space, style: "display: block" %>
    <%= form.number_field :parking_space , class: "form-control"%>
  </div>
  <div class = "form-group">
    <%= form.label :details, style: "display: block" %>
    <%= form.text_area :details , class: "form-control"%>
  </div>
  <div class = "form-group">
    <%= form.label :photo%>
    <%= form.file_field :photo, class: "form-control"%>
    <%= form.hidden_field :photo_cache%>
  </div>
  <div class = "mt-5">
    <%if @property.photo.present?%>
    <%= property_thumbnail(@property,"250px","250px")%>
    <%end%>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class:"btn btn-lg mt-3 btn-success"%>
  </div>
<% end %>

app/views/properties/_latest_properties.html.erb
<% @properties.each do |property| %>
    <div class="col-4 mt-5">
        <div class="card shadow-sm">
           <%=link_to( property_thumbnail(property,"100%","225px"), property_path(property),class: "bd-placeholder-img card-img-top" )%>
           <div class="card-body">
                <h3 class="card-title"><%= link_to property.name ,property_path(property) %></h3>
                <p class="card-text"><%= property.address%></p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="amenities">
                        <span><i class="bi bi-door-closed-fill"></i> <%= property.rooms%></span> |
                        <span><i class="bi bi-people"> <%= property.bath_rooms%></i></span> |
                        <span><i class="bi bi-tag-fill"></i> <%= number_to_currency(property.price ,precision: 0 )%></span>
                    </div>
                    <small class="text-muted"><%=created_before_time(property)%></small>
                 </div>
            </div>
        </div>
    </div>

<% end %>

app/views/properties/edit.html.erb
<h1 class= "h3">Editing property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Show this property", @property %> |
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class = "h3">Properties</h1>
<%= link_to "New property", new_property_path %>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">Photo</th>
        <th scope="col">Name</th>
        <th scope="col">Address</th>
        <th scope="col">Price</th>
        <th scope="col">Rooms</th>
        <th scope="col">Bath Rooms</th>
        <th scope="col">Parking Space</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @properties.each do |property| %>
        <tr>
          <td><%= image_tag(property.photo,style:"width:50px ; height:50px;")%></td>
          <td><%= property.name %></td>
          <td><%= property.address %></td>
          <td><%= property.price %></td>
          <td><%= property.rooms %></td>
          <td><%= property.bath_rooms %></td>
          <td><%= property.parking_space %></td>
          <td><%= link_to "Show", property %></td>
          <td><%= link_to "Edit", edit_property_path(property) %></td>
          <td><%= link_to "Destroy", property, data: {turbo_method: :delete, turbo_confirm: 'Are you sure'} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/properties/new.html.erb
<h1 class ="h3">New property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @property %>


<div>
  <%# <%= link_to "Edit this property", edit_property_path(@property) %>
  <%= link_to "Back to properties", properties_path %>


</div>